from typing import Protocol
from uuid import UUID

from app.modules.dashboards_custom.domain.entities import DashboardCustomEntity, DashboardCustomSummary


class DashboardCustomRepository(Protocol):
    async def get_by_id(self, dashboard_id: UUID) -> DashboardCustomEntity | None: ...

    async def get_summary_by_id(self, dashboard_id: UUID) -> DashboardCustomSummary | None: ...

    async def list_accessible_to(self, user_id: UUID, project_id: UUID | None) -> list[DashboardCustomSummary]: ...

    async def create(self, dashboard: DashboardCustomEntity) -> DashboardCustomEntity: ...

    async def update(self, dashboard: DashboardCustomEntity) -> DashboardCustomEntity: ...

    async def delete(self, dashboard_id: UUID) -> None: ...
