from typing import Protocol
from uuid import UUID

from app.modules.departments.domain.entities import DepartmentEntity, DepartmentSummary


class DepartmentRepository(Protocol):
    async def get_by_id(self, department_id: UUID) -> DepartmentEntity | None: ...

    async def get_summary_by_id(self, department_id: UUID) -> DepartmentSummary | None: ...

    async def list_by_project(self, project_id: UUID) -> list[DepartmentSummary]: ...

    async def search(self, query: str | None) -> list[DepartmentSummary]: ...

    async def create(self, department: DepartmentEntity) -> DepartmentEntity: ...

    async def update(self, department: DepartmentEntity) -> DepartmentEntity: ...

    async def delete(self, department_id: UUID) -> None: ...
