from typing import Protocol

from app.modules.forms.domain.entities import FormEntity, FormField, FormSettings, FormStatus, TemplateBox


class FormRepository(Protocol):
    async def get_by_id(self, form_id: str) -> FormEntity | None: ...

    async def search(self, query: str | None, status: FormStatus | None, project_id: str | None) -> list[FormEntity]: ...

    async def create(self, form: FormEntity) -> FormEntity: ...

    async def update_fields(self, form_id: str, fields: list[FormField]) -> None: ...

    async def update_settings(self, form_id: str, settings: FormSettings) -> None: ...

    async def update_template(self, form_id: str, template: list[TemplateBox]) -> None: ...

    async def update_template_pdf(self, form_id: str, file_key: str | None) -> None: ...

    async def rename(self, form_id: str, name: str, description: str) -> None: ...

    async def set_status(self, form_id: str, status: FormStatus) -> None: ...

    async def increment_attendances_count(self, form_id: str) -> None: ...

    async def delete(self, form_id: str) -> None: ...
