from typing import Protocol
from uuid import UUID

from app.modules.permissions.domain.entities import (
    PermissionGroupEntity,
    PermissionGroupSummary,
    ResourcePermission,
)


class PermissionGroupRepository(Protocol):
    async def get_by_id(self, group_id: UUID) -> PermissionGroupEntity | None: ...

    async def search(self, query: str | None, project_ids: list[UUID] | None = None) -> list[PermissionGroupSummary]: ...

    async def get_summary_by_id(self, group_id: UUID) -> PermissionGroupSummary | None: ...

    async def create(self, group: PermissionGroupEntity) -> PermissionGroupEntity: ...

    async def update(self, group: PermissionGroupEntity) -> PermissionGroupEntity: ...

    async def delete(self, group_id: UUID) -> None: ...

    async def set_group_permissions(self, group_id: UUID, permissions: list[ResourcePermission]) -> None: ...

    async def get_member_ids(self, group_id: UUID) -> list[UUID]: ...

    async def set_members(self, group_id: UUID, user_ids: list[UUID]) -> None: ...

    async def get_group_ids_for_user(self, user_id: UUID) -> list[UUID]: ...


class UserPermissionRepository(Protocol):
    async def get_user_permissions(self, user_id: UUID) -> list[ResourcePermission]: ...

    async def set_user_permissions(self, user_id: UUID, permissions: list[ResourcePermission]) -> None: ...

    async def get_permissions_for_groups(self, group_ids: list[UUID]) -> list[ResourcePermission]: ...
