"""add device journey requirement flags

Revision ID: 4a762aa0f71c
Revises: 04463f63de32
Create Date: 2026-07-20 14:17:35.329049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a762aa0f71c'
down_revision: Union[str, None] = '04463f63de32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('require_journey_photo', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('devices', sa.Column('require_journey_gps', sa.Boolean(), server_default='true', nullable=False))
    op.create_foreign_key('fk_organizations_admin_id', 'organizations', 'users', ['admin_id'], ['id'], ondelete='RESTRICT', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_organizations_admin_id', 'organizations', type_='foreignkey')
    op.drop_column('devices', 'require_journey_gps')
    op.drop_column('devices', 'require_journey_photo')
    # ### end Alembic commands ###
