"""add document imports table

Revision ID: 884523f97cc8
Revises: e05dabcb1ec3
Create Date: 2026-07-20 16:52:57.519423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884523f97cc8'
down_revision: Union[str, None] = 'e05dabcb1ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.String(length=24), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_file_key', sa.String(length=500), nullable=False),
    sa.Column('source_filename', sa.String(length=300), nullable=False),
    sa.Column('extracted_fields', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attendance_id', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_imports')
    # ### end Alembic commands ###
