"""add whatsapp authorizations and conversations tables

Revision ID: dce5be3aadcf
Revises: 884523f97cc8
Create Date: 2026-07-20 18:56:45.990748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dce5be3aadcf'
down_revision: Union[str, None] = '884523f97cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_authorizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_authorizations_phone_number'), 'whatsapp_authorizations', ['phone_number'], unique=True)
    op.create_table('whatsapp_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('authorization_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('form_id', sa.String(length=24), nullable=True),
    sa.Column('current_field_index', sa.Integer(), nullable=False),
    sa.Column('pending_options', sa.JSON(), nullable=False),
    sa.Column('text_answers', sa.JSON(), nullable=False),
    sa.Column('photo_answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authorization_id'], ['whatsapp_authorizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_conversations_phone_number'), 'whatsapp_conversations', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_conversations_phone_number'), table_name='whatsapp_conversations')
    op.drop_table('whatsapp_conversations')
    op.drop_index(op.f('ix_whatsapp_authorizations_phone_number'), table_name='whatsapp_authorizations')
    op.drop_table('whatsapp_authorizations')
    # ### end Alembic commands ###
