from typing import Protocol
from uuid import UUID

from app.modules.documents.domain.entities import DocStatus, DocumentEntity, DocumentTemplateEntity


class DocumentRepository(Protocol):
    async def get_by_id(self, document_id: UUID) -> DocumentEntity | None: ...

    async def get_by_validation_code(self, validation_code: str) -> DocumentEntity | None: ...

    async def get_by_attendance_id(self, attendance_id: str) -> DocumentEntity | None: ...

    async def search(self, query: str | None, status: DocStatus | None, project_id: UUID | None) -> list[DocumentEntity]: ...

    async def create(self, document: DocumentEntity) -> DocumentEntity: ...

    async def update(self, document: DocumentEntity) -> DocumentEntity: ...


class DocumentTemplateRepository(Protocol):
    async def get_by_id(self, template_id: UUID) -> DocumentTemplateEntity | None: ...

    async def list_by_project(self, project_id: UUID) -> list[DocumentTemplateEntity]: ...

    async def create(self, template: DocumentTemplateEntity) -> DocumentTemplateEntity: ...

    async def update(self, template: DocumentTemplateEntity) -> DocumentTemplateEntity: ...

    async def delete(self, template_id: UUID) -> None: ...
