from typing import Protocol
from uuid import UUID

from app.modules.whatsapp_auth.domain.entities import WhatsAppAuthorizationEntity, WhatsAppAuthorizationSummary


class WhatsAppAuthorizationRepository(Protocol):
    async def get_by_id(self, authorization_id: UUID) -> WhatsAppAuthorizationEntity | None: ...

    async def get_by_phone(self, phone_number: str) -> WhatsAppAuthorizationEntity | None: ...

    async def search(self, query: str | None, project_id: UUID | None) -> list[WhatsAppAuthorizationSummary]: ...

    async def create(self, authorization: WhatsAppAuthorizationEntity) -> WhatsAppAuthorizationEntity: ...

    async def update(self, authorization: WhatsAppAuthorizationEntity) -> WhatsAppAuthorizationEntity: ...

    async def delete(self, authorization_id: UUID) -> None: ...
