from typing import Protocol
from uuid import UUID

from app.modules.projects.domain.entities import ProjectEntity, ProjectSummary


class ProjectRepository(Protocol):
    async def get_by_id(self, project_id: UUID) -> ProjectEntity | None: ...

    async def get_summary_by_id(self, project_id: UUID) -> ProjectSummary | None: ...

    async def search(self, query: str | None) -> list[ProjectSummary]: ...

    async def create(self, project: ProjectEntity) -> ProjectEntity: ...

    async def update(self, project: ProjectEntity) -> ProjectEntity: ...

    async def delete(self, project_id: UUID) -> None: ...
