from typing import Protocol
from uuid import UUID

from app.modules.reports.domain.entities import ReportEntity, ReportSummary, ReportType


class ReportRepository(Protocol):
    async def get_by_id(self, report_id: UUID) -> ReportEntity | None: ...

    async def get_summary_by_id(self, report_id: UUID) -> ReportSummary | None: ...

    async def search(self, query: str | None, type_: ReportType | None, project_id: UUID | None) -> list[ReportSummary]: ...

    async def create(self, report: ReportEntity) -> ReportEntity: ...

    async def update(self, report: ReportEntity) -> ReportEntity: ...

    async def delete(self, report_id: UUID) -> None: ...
